### PR TITLE
Feature/scroll ele

### PR DESCRIPTION
**Pull request by eacaps**
Hello, I was looking into using a infinite-scroller library and yours seemed like the simplest and most up to date. Unfortunately the view is complicated and the scroll container is several levels up from the actual scrolling list.  Our page also has a header and the useWindow property will not produce the correct scrolling behavior. I implemented an additional property `scrollElement` that you can specify as the element to attach the scroll handlers to. Let me know if you think this is a reasonable idea.

### CODE REVIEW

**Comment by calebcassel** [comment]
I'd love to see this included. This is exactly what I need right now, as the `useWindow` prop just doesn't provide enough flexibility.

**Comment by danbovey** [comment]
Hi

If I've got this right, you don't want the `parentNode` to be the scrolling element. Passing around DOM elements in props is definitely not idiomatic to React. @calebcassel I get that choosing between window or parent might be inflexible but I just don't see the use case for this.

Look into [react-dimensions](https://github.com/digidem/react-dimensions) if the `parentNode` of your InfiniteScroll component isn't taking up the required space.

https://github.com/CassetteRocks/react-infinite-scroller#dom-scroll-events

Also, creating a new prop called `scrollElement` whilst leaving `useWindow` a boolean is weird logic allowing you to ask for window and provide a scroll element - would need to be rethought into something like define a scroll element, else use window.

**Comment by eacaps** [comment]
I agree that passing around DOM elements is not idiomatic to React, but there are times where things don't quite fit into the 'React way of thinking' - and as you said, you've already included `useWindow` as an option. I agree that the combination of scrollElement and useWindow is confusing, I would be willing to modify my code to allow the `window` to be passed as a `scrollElement` and provide backwards compatibility by allowing `useWindow` to automatically set the scrollElement to `window` regardless of whether another scrollElement is specified.

If you're still against these changes, that's okay with me, close the pull request and I'll just use my fork for now. I will look into using react-dimensions but I still think without significant styling adjustments in my project it will be difficult to achieve the proper look that the flexibility of specifying the `scrollElement` would achieve.

I'll just give you some details about our view in an attempt to explain. The view I'm trying to use infinite scroll for is similar to twitter's main logged-in view. We've got a header up top and a horizontal flexbox of 3 columns below it(I'll refer to this as the main viewport). The middle column has the main content that I would like to allow infinite scrolling but I would prefer the scrollbar remain locked to the main viewport rather than stuck in the middle of the screen with the content. Because there are many nested components within each column the direct parent of the middle column is not the main viewport so I had to improvise and experiment with adding a `scrollElement`. Doing so allowed me to achieve the desired look with the least headaches from having to deal with refactoring the layout and styles.

**Comment by calebcassel** [comment]
I can see that passing DOM nodes isn't preferrable to something like using composition, but in my case I am developing a package where I have no way of controlling where my component will be placed by third parties. Coincidentally, I as one of those third parties have an issue where `window` can't be scrollable element, and because of some 3D transforms on the page, there's no way to make the direct parent to be the scrollable element either.

I did come across `react-waypoint` today which essentially does what we are discussing via a `scrollableAncestor` attribute. https://www.npmjs.com/package/react-waypoint

**Comment by mxstbr** [comment]
For my app we have a `PostFeed` component which renders a list of posts. (duh) This `PostFeed` is then rendered in different place in the app but, crucially, isn't the only thing that scrolls: the sidebar scrolls with it.

```
+-----------------------------------------------------------------------+
|                                                                       |
|                           ScrollContainer                             |
|                                                                       |
|        +--------------+  +-----------------------------+              |
|        |              |  |          PostFeed           |              |
|        |              |  | +-------------------------+ |              |
|        |              |  | |                         | |              |
|        |              |  | |                         | |              |
|        |              |  | |        Post             | |              |
|        |              |  | |                         | |              |
|        |              |  | +-------------------------+ |              |
|        |              |  |                             |              |
|        |  Sidebar     |  | +-------------------------+ |              |
|        |              |  | |                         | |              |
|        |              |  | |                         | |              |
|        |              |  | |        Post             | |              |
|        |              |  | |                         | |              |
|        |              |  | +-------------------------+ |              |
|        |              |  |                             |              |
|        |              |  | +-------------------------+ |              |
|        |              |  | |                         | |              |
|        |              |  | |                         | |              |
|        |              |  | |        Post             | |              |
|        +--------------+  | |                         | |              |
|                          | +-------------------------+ |              |
|                          |                             |              |
|                          | +-------------------------+ |              |
|                          | |                         | |              |
|                          | |                         | |              |
+--------------------------+-+-------------------------+-+--------------+

```

When scrolled not only the list of post scrolls but the whole scroll container including the sidebar. I need this patch to be able to specify that container as the element to listen to instead of the `PostFeed`. 

While I agree that there might be some confusion around `useWindow` and `scrollElement` I think `useWindow` could just be a special shorthand of `scrollElement={window}` to make this a non-breaking change that in the next version will be deprecated.

What do you think?

**Comment by mxstbr** [comment]
I pulled this PR and published that version as `react-infinite-scroller-with-scroll-element`, but I'd love to get support for that in core and not rely on outdated code 😅

**Comment by danbovey** [comment]
The solution to this was made in #58.

**Pull request closed without merging**
