### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by anupvarghese**
- Add `eslint` 
- Add basic testing using `enzyme`, `mocha`, to start the formal testing (https://github.com/CassetteRocks/react-infinite-scroller/issues/2)
- Add coverage and reporting using `nyc`, `istanbul`
- Update `README` to include `yarn` for installation
- Add travis for build

### CODE REVIEW

**Comment by anupvarghese** [comment]
@danbovey please review

**Comment by danbovey** [comment]
Looks great! Thanks so much for doing this.

**Comment by danbovey** [comment]
My only nit-pick is that I personally dislike `eslint` and prefer `prettier`. I might replace it out later if prettier doesn't add too many extra LOC.

It's little things like eslint turning a one line import statement into

```js
import React, {
  Component,
} from 'react';
```

or this monstrosity

```js
offset = this.calculateTopPosition(el) +
                     (el.offsetHeight -
                     scrollTop -
                     window.innerHeight);
```

**Comment by anupvarghese** [comment]
@danbovey No problem. Also, i noticed a typo in readme 
this 
`yarn add install react-infinite-scroller`  should be `yarn add react-infinite-scroller`

Also, you may have to give a travis access for builds & then we can add a build badge.

**Comment by danbovey** [comment]
Fixed!

And travis - will do :)

**Pull request merged**
