### PR TITLE
feat(scrollElementSelector): add support for scrollElementSelector

### PR DESCRIPTION
**Pull request by nayish1**
Allows to add infinite scroll functionality on custom element by selector.

### CODE REVIEW

**Comment by brandon-dewitt** [comment]
@danbovey is can this be merged?

**Comment by gandazgul** [comment]
We need this in order to be able to use this component. Is great otherwise, thank you!

**Comment by scottcanoni** [comment]
I would also like to use this component but I require this fix.

@danbovey, can this please be merged soon?

**Comment by danbovey** [comment]
The solution to this was made in #58.

**Pull request closed without merging**
