### PR TITLE
Add a passthrough for the ref prop

### PR DESCRIPTION
**Pull request by defrex**
I need access to the DOM element to manage scroll position in a chat-style application. This PR adds a simple passthrough for `ref`

### CODE REVIEW

**Comment by defrex** [comment]
Turns out my need for a `ref` passthrough was based on a misunderstanding. I thought `InfiniteScroll`'s node had the overflow.

Nevertheless, this could be useful for someone.

**Comment by danbovey** [comment]
Had the same thing come in to question the other day but with the `className` prop. All props that aren't on the list on [L43](https://github.com/CassetteRocks/react-infinite-scroller/blob/master/src/InfiniteScroll.js#L43) are passed through to the rendered div. `ref` should be no different.

**Comment by defrex** [comment]
`ref` is different, since you override it explicitly. Either way, I don't need it anymore.

**Comment by danbovey** [comment]
Published in `1.0.15`. Didn't merge this PR as it's got some weird changes in `dist` and whitespace in `src`.

**Pull request closed without merging**
