### PR TITLE
Added getParentElement function that can be easily overridden to add functionality

### PR DESCRIPTION
**Pull request by deibeljc**
Given the discussion in #38, it doesn't make sense to add in the prop and functionality to pass in a scroll parent. The next best thing is to have a way to easily escape hatch it on the consumption side. Overall the idea here is that the consumer can extend InfiniteScroll and then implement their own getParentElement function so that they can still customize it a little bit without having to keep and maintain a fork!

### CODE REVIEW

**Comment by danbovey** [comment]
How do you override the `getParentElement` method?

**Comment by deibeljc** [comment]
It would look something like this: 

```js
class InfiniteScrollOverride extends InfiniteScroll {

    /**
     * We are overriding the getParentElement function so we don't have
     * to monkey-patch the original library or have to fork and maintain
     * that fork!
     *
     * @param {any} el the scroller domNode
     * @returns {any} the parentNode to base the scroll calulations on
     *
     * @memberOf InfiniteScrollOverride
     */
    getParentElement(el) {
        if (this.props.scrollParent) {
            return this.props.scrollParent;
        }
        return super.getParentElement(el);
    }

    render() {
        return super.render();
    }
}
```

**Comment by deibeljc** [comment]
@danbovey in response to your edit, that is not quite how it would be overridden. If you look above you still have access to the super method so you can add conditional prop checks and if those fail then default back to whatever is in the super code! It is a relatively elegant way to extend the functionality without monkey patching like you described above.

**Comment by AlexandrAnash** [comment]
It would be very cool to get these changes!
The only thing you need get latest version branch master 
In the near future is planned merge?

**Comment by deibeljc** [comment]
@jomo24 not sure I have a working example atm since these changes never got merged in.

**Comment by deibeljc** [comment]
@danbovey I merged back into master so this should be good to go!

**Comment by deibeljc** [comment]
looks like the CI is failing for a yarn connection issue?

**Comment by deibeljc** [comment]
ping @danbovey

**Comment by callmetwan** [comment]
@danbovey I know you are busy. When you have a moment will you merge this in? Thanks!

**Comment by callmetwan** [comment]
@deibeljc It looks like your commit Merged Back Into Master https://github.com/CassetteRocks/react-infinite-scroller/pull/58/commits/96ec1bf1838cd3a66f7a4c6d1efc7b735e24bbcb actually removed the guts of the functionality you added. If you take a peak at your repo you'll see that getParentElement isn't actually called anywhere.

**Comment by deibeljc** [comment]
@callmetwan oh wait really!? Lol. That is funny. Let me take a look

**Comment by deibeljc** [comment]
@danbovey @callmetwan Fixed my merging issue. Should be ready to go now!

**Comment by danbovey** [comment]
Thanks for all the work! Released in `1.2.0`.

**Comment by DenisNeustroev** [comment]
Please, provide an example with typescript 🙇‍♂️

**Pull request merged**
