### PR TITLE
Fixed local state update on hiding loader element

### PR DESCRIPTION
**Pull request by Nikit0s**
PR for Issue #124 
The main problem is that with this fix we must set key property to loader component to avoid warning messages.

### CODE REVIEW

**Comment by Nikit0s** [comment]
@danbovey review please

**Comment by danbovey** [comment]
Looks good, thanks!

**Comment by janhartmann** [comment]
For other readers, if you are getting this error: `Check the render method of `InfiniteScroll`. It was passed a child from TableComponent. See https://fb.me/react-warning-keys for more information.` 

You should append key={0} or something on:

```
 <InfiniteScroll
                pageStart={0}
                loadMore={loadMoreEntries}
                hasMore={true}
                useWindow={false}
                initialLoad={false}
                loader={
                    <div className={classes.loading} key={0}> <--- here
                        <LoadingIndicator loading={loading} error={error} />
                    </div>
                }
            >
```

**Comment by danbovey** [comment]
Adding to README. Thanks @janhartmann!

**Comment by janhartmann** [comment]
Would it be possible to utilize `<React.Fragment />`  in this case? https://reactjs.org/docs/fragments.html

**Pull request merged**
