### PR TITLE
Do not add undefined to children if loader is not defined

### LINKED ISSUE #80: Element type is invalid (TypeScript)
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `AtomicTagsView`.
```

In my `AtomicTagsView`:
```typescript
import * as React from 'react';
import InfiniteScroll from 'react-infinite-scroller';

// In the render method
                <InfiniteScroll
                    element="tbody"
                    className="dc-table__tbody"
                    loadMore={fetchAtomicTags}
                >
                    // Here are some rows that were working previous to InfiniteScroll
                </InfiniteScroll>
```

I have created my own type definitions for the module (PR pending in DefinitelyTyped-repo):
```typescript

declare module 'react-infinite-scroller' {
    import * as React from 'react';

    /**
     * <InfiniteScroll /> properties.
     */
    interface InfiniteScrollProps extends React.HTMLProps<InfiniteScroll> {
        /**
         * Name of the element that the component should render as.
         * Defaults to 'div'.
         */
        element?: string;
        /**
         * Whether there are more items to be loaded. Event listeners are removed if false.
         * Defaults to false.
         */
        hasMore?: boolean;
        /**
         * Whether the component should load the first set of items.
         * Defaults to true.
         */
        initialLoad?: boolean;
        /**
         * Whether new items should be loaded when user scrolls to the top of the scrollable area.
         * Default to false.
         */
        isReverse?: boolean;
        /**
         * A callback for when more items are requested by the user.
         */
        loadMore(): void;
        /**
         * The number of the first page to load, with the default of 0, the first page is 1.
         * Defaults to 0.
         */
        pageStart?: number;
        /**
         * The distance in pixels before the end of the items that will trigger a call to loadMore.
         * Defaults to 250.
         */
        threshold?: number;
        /**
         * Proxy to the useCapture option of the added event listeners.
         * Defaults to false.
         */
        useCapture?: boolean;
        /**
         * Add scroll listeners to the window, or else, the component's parentNode.
         * Defaults to true.
         */
        useWindow?: boolean;
    }

    export default class InfiniteScroll extends React.Component<InfiniteScrollProps, any> { }
}
```

### PR DESCRIPTION
**Pull request by Lapanti**
See #80 
Resolves #80

### CODE REVIEW

**Comment by danbovey** [comment]
I just merged a PR that supports placing the loader before items if `isReverse` is true. So this PR will need a change where the loader is added with `unshift` to the children array instead of `push`. See if you can simplify it?

**Comment by Lapanti** [comment]
@danbovey will do tomorrow 👍

**Comment by Lapanti** [comment]
@danbovey done :)

**Comment by vitalybaev** [comment]
Any update of this, guys?

**Comment by Lapanti** [comment]
Fixed the failing Travis build (sorry hadn't noticed that previously)

**Comment by danbovey** [comment]
Thanks! Published in `1.0.14`.

**Pull request merged**
