### PR TITLE
Add prop-types as a peer dependency

### PR DESCRIPTION
**Pull request by ahstro**
Should either be regular dep or peer, but peer seemed more appropriate.

### CODE REVIEW

**Comment by ahstro** [comment]
Done and done :)

**Comment by forrestbice** [comment]
Will this close https://github.com/CassetteRocks/react-infinite-scroller/issues/72? Also @danbovey looks like this is ready for another review pass

**Comment by danbovey** [comment]
Thanks @ahstro! Thanks for the notification @forrestbice. Published in `1.0.11`

**Comment by MichaelDeBoey** [comment]
@danbovey @ahstro `prop-types` should be a regular dependency
If someone's using `React` without the `prop-types` package, they would have it as a dependency just for this package, which is cluttering their `package.json`

**Comment by danbovey** [comment]
true...

**Comment by ahstro** [comment]
Hmm, yeah, didn't think about that. Thanks :) Would you just fix that @danbovey (if you want it that way)? Feels unnecessarily small to create a PR for, especially when you know about it 😅

**Comment by MichaelDeBoey** [comment]
Fixed this in #76

**Pull request merged**
