### PR TITLE
update react v16.0.0

### PR DESCRIPTION
**Pull request by akichim21**
update react v16.0.0
no problem: npm run test & browser test

### CODE REVIEW

**Comment by danbovey** [comment]
Needs to be `"^0.14.9 || ^15.3.0 || ^16.0.0"`

**Comment by akichim21** [comment]
fix review
&
can't update devDependencies react & react-dom v16.0.0
because chai-enzyme don't correspond to react v16
https://github.com/producthunt/chai-enzyme/issues/199

**Comment by akichim21** [comment]
delete chai-enzyme
if it's not good , I will remake pull request.

**Comment by tpanganamala** [comment]
Waiting on this to get merged to use Reactv16. Any ETA would be appreciated :)

**Comment by akichim21** [comment]
update README.md.
I will fix it if there are other problems.

**Comment by danbovey** [comment]
Released in `1.1.0`

**Pull request merged**
