### PR TITLE
fix 183 When isReverse is true,The scroll bar position incorrect

### PR DESCRIPTION
**Pull request by hengkx**
ref #183

### CODE REVIEW

**Comment by danbovey** [comment]
Thanks. I don't know how this has gone unnoticed this long!

**Comment by ratchapol-an** [comment]
Could I ask When do you guys think this PR is going be merged and released?

**Comment by eric7578** [comment]
Thanks for the work! I was looking for the problem and find this PR!

**Comment by SteveAquino** [comment]
Mentioned a work around in case anyone is still waiting on this: https://github.com/CassetteRocks/react-infinite-scroller/issues/183#issuecomment-443371529

**Comment by eric7578** [comment]
May I ask is there any plan for merging this PR?

**Comment by danbovey** [comment]
Released in version `1.2.3`!

**Pull request merged**
