### PR TITLE
added reset function and componentWillReceiveProps

### PR DESCRIPTION
**Pull request by vanhtuan0409**
This is a pull-request remake from this original [pull-request](https://github.com/guillaumervls/react-infinite-scroll/pull/29)
I also added support for ImmutableJS

### CODE REVIEW

**Comment by Flyover-ArtSk** [comment]
11 days ago..

**Comment by aboe026** [comment]
+1 I really need the functionality as well...please merge

**Comment by danbovey** [comment]
Will test this tomorrow 😃

**Comment by vanhtuan0409** [comment]
Glad to hear about it 😃

**Comment by danbovey** [comment]
Published in `1.0.5`

**Comment by sommcz** [comment]
hi, for brief info: new version stops calling loadMore callback at my app.
Has any one same problem?
I dont have time to look into it more deeply - so i just downgraded back to 1.0.4 for now and all is working again.

**Comment by danbovey** [comment]
Hi, really sorry.

I had a bad feeling about this PR to start with. My test didn't run the latest code because the `docs` folder used `react-infinite-scroller` directly and I didn't run `npm update`, thought it was linked to the dist folder in master! Reverting this change for now, you can unlock your version and update.

**Comment by sommcz** [comment]
ok. 1.0.6 works fine. thanx.

**Pull request merged**
